### ISSUE TITLE
It does not work with Intellij 2017.3

### ISSUE THREAD

**Issue by goldyliang** [JFrogDev/jfrog-idea-plugin#1]
It works fine with Intellij 2016.2.

However in Intellij 2017.3, only component dependency graph is shown, but no any vulnerabilities displayed.

**Comment by romangurevitch** [comment]
@goldyliang, 
Thanks for reporting this issue, we have committed a fix that can be viewed [here](https://github.com/JFrogDev/jfrog-idea-plugin/commit/9d8c2adf81154ce74283c4cd86fd478c57aec608).
We have released version 1.0.1 of the plugin and it will be available in IntelliJ IDEA in a couple of days.
Manual download available [here](https://bintray.com/jfrog/jfrog-jars/download_file?file_path=org%2Fjfrog%2Fidea%2F1.0.1%2FJFrog-1.0.1.zip).

**Comment by eyalbe4** [comment]
@goldyliang, I'm closing this issue for now.

**Comment by goldyliang** [comment]
Thank you!
